#!/bin/sh
# Pack a raw 8086 binary with BCJ + LZSA2, emit a C header with the bytes.
#
# Usage: pack.sh <input.bin> <symbol_name> <output.h>
#
# Produces a header defining:
#   #define <NAME>_RAW_SIZE     <bytes>
#   #define <NAME>_PACKED_SIZE  <bytes>
#   static const unsigned char <name>_packed[...] = { ... };
#
# Builds bcj16 and the lzsa CLI on first run.

set -eu

INPUT=${1:-}
NAME=${2:-}
OUTPUT=${3:-}

if [ -z "$INPUT" ] || [ -z "$NAME" ] || [ -z "$OUTPUT" ]; then
    echo "usage: $0 <input.bin> <symbol_name> <output.h>" >&2
    exit 1
fi

ROOT=$(cd "$(dirname "$0")/.." && pwd)
BCJ16=$ROOT/build/bcj16
LZSA=$ROOT/vendor/lzsa/lzsa

if [ ! -x "$BCJ16" ]; then
    echo "building bcj16..." >&2
    mkdir -p "$ROOT/build"
    cc -O2 -Wall -o "$BCJ16" "$ROOT/tools/bcj16.c"
fi

if [ ! -x "$LZSA" ]; then
    echo "building lzsa CLI..." >&2
    (cd "$ROOT/vendor/lzsa" && make -s) >&2
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

RAW_SIZE=$(wc -c < "$INPUT" | tr -d ' ')

"$BCJ16" -e < "$INPUT" > "$TMP/filt.bin"
"$LZSA" -f 2 -r "$TMP/filt.bin" "$TMP/filt.lzsa" >/dev/null

PACKED_SIZE=$(wc -c < "$TMP/filt.lzsa" | tr -d ' ')

UPPER=$(echo "$NAME" | tr '[:lower:]' '[:upper:]')

{
    echo "/* Generated by tools/pack.sh — do not edit. */"
    echo "/* Source: $INPUT  raw=${RAW_SIZE}  packed=${PACKED_SIZE} */"
    echo
    echo "#ifndef ${UPPER}_H"
    echo "#define ${UPPER}_H"
    echo
    echo "#define ${UPPER}_RAW_SIZE     ${RAW_SIZE}u"
    echo "#define ${UPPER}_PACKED_SIZE  ${PACKED_SIZE}u"
    echo
    echo "static const unsigned char ${NAME}_packed[${PACKED_SIZE}] = {"
    xxd -i < "$TMP/filt.lzsa" | sed 's/^/    /'
    echo "};"
    echo
    echo "#endif"
} > "$OUTPUT"

ratio=$(awk "BEGIN { printf \"%.1f\", ${PACKED_SIZE} * 100 / ${RAW_SIZE} }")
echo "${NAME}: ${RAW_SIZE} B -> ${PACKED_SIZE} B (${ratio}%) -> ${OUTPUT}" >&2
